NetworkPkg/NvmeOfDxe: DHCP4 include Option61
timberland-sig/edk2 pull request #30
Opened 2024-02-16 20:27 UTC by trevor-cockrell

Provide DHCP Option61 (ClientID) to prevent OS receiving potential address mismatch from that reported in NBFT, resulting in connection failures.

2024-02-22 19:27 UTC, johnmeneghini reviewed
I will give this branch a test before I approve this MR.

2024-04-04 21:48 UTC, mwilck commented
As noted in the Timberland SIG call today:

This patch adds a DHCP client identifier option in RFC 2132 format, which is deprecated by [RFC 4361](https://datatracker.ietf.org/doc/html/rfc4361). From §6.1: "*DHCPv4 clients conforming to this specification MUST use stable DHCPv4 node identifiers in the dhcp-client-identifier option.  DHCPv4 clients MUST NOT use client identifiers based solely on layer two addresses that are hard-wired to the layer two device (e.g., the ethernet MAC address) as suggested in RFC 2131*".

RFC 4361 goes on to say that "*DHCPv4 servers that conform to this specification MUST use the 'client identifier' option to identify the client if the client sends it ... DHCPv4 servers MUST use 'chaddr' as an identifier in cases where 'client identifier' is not sent*" (chaddr is the MAC address for practical purposes).

While I agree with @johnmeneghini that the simple RFC 2132 identifier "works" in most cases [^works], I think we shouldn't implement a technique in 2024 that has been deprecated since 18 years.

The quotes above show that DHCPv4 servers MUST treat a client that sends no DHCP identifier at all exactly like clients that send an RFC 2132 identifier like we do here. Therefore I don't expect that this patch has any practical significance, except that a RFC 4361-compliant identifier used by an OS client (like wicked for example) will now explicitly differ from the identifier used by the client.

If you observed a different behavior with this patch in some environment, I'd like to understand what kind of DHCP server was used in that environment.

[^works]: The reason that it "works" is precisely that servers treat it as if no client id had been sent at all.

2024-04-04 21:50 UTC, mwilck requested changes
For the reasons stated in above, I currently don't see this as an improvement.

2024-04-18 16:31 UTC, mwilck approved these changes
After discussion in today's meeting: My previous remarks still stand, but I don't think these changes will do harm, and it makes Timberland EDK2 behave similarly to the Dell BIOS, so I'm approving it now.

2024-08-29 16:18 UTC, merged